apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.tlsSecretName }}
  labels:
    {{- include "kubernetes-dashboard.labels" (index .Subcharts "kubernetes-dashboard") | nindent 4 }}
  annotations:
    {{- include "kubernetes-dashboard.annotations" (index .Subcharts "kubernetes-dashboard") | nindent 4 }}
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  {{- include "kubernetes-dashboard.proxy-certs" . | nindent 2 }}
