apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.tlsSecretName }}
  labels:
    {{- include "kubernetes-dashboard.labels" (index .Subcharts "kubernetes-dashboard") | nindent 4 }}
  annotations:
    {{- include "kubernetes-dashboard.annotations" (index .Subcharts "kubernetes-dashboard") | nindent 4 }}
    {{- include "kubernetes-dashboard.tls-secret-annotations" . | nindent 4 }}
data:
  {{- include "kubernetes-dashboard.proxy-certs" . | nindent 2 }}
